sudo: required
dist: trusty
language: node_js
node_js:
  - '7.0.0'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd ng2-aot-appworks
  
before_script:
- npm install -g npm
- npm install -g @angular/cli
- npm install -g lite-server
- npm install
- ng build
